apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccnp-perf
spec:
  selector:
    matchLabels:
      app: ccnp-perf
  template:
    metadata:
      labels:
        app: ccnp-perf
    spec:
      containers:
      - name: ccnp-perf
        image: "docker.io/library/ccnp-perf:latest"
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            tdx.intel.com/tdx-guest: 1
          requests:
              tdx.intel.com/tdx-guest: 1
      nodeSelector:
        intel.feature.node.kubernetes.io/tdx-guest: enabled
