name: Run CCNP E2E test
on:
  schedule:
    - cron: '0 7 * * *'
  pull_request:
    paths:
      - '.github/workflows/e2e-test-k8s.yaml'
      - 'deployment/**'
      - 'container/**'
      - 'sdk/**'
  workflow_dispatch:

jobs:
  E2E_test:
    runs-on: tdvm-ut
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: Build and push CCNP images
        run: |
          sudo ./container/build.sh -r gar-registry.caas.intel.com/cpio -g latest
      - name: Deploy CCNP server
        run: |
          sudo ./deployment/kubernetes/script/deploy-ccnp.sh -r gar-registry.caas.intel.com/cpio -g latest -d
      - name: Deploy CCNP test pod
        run: |
          sudo ./deployment/kubernetes/script/deploy-ccnp-example.sh -r gar-registry.caas.intel.com/cpio -g latest -d
      - name: Run Test
        run: |
           sudo ./test/ci-test/ci-e2e-test.sh
